Attempt to create a RelaxNG that could describe external blocks in parallel with normal blockx. Unfortunately, it leads to conflicts in the scheme:
Traceback (most recent call last):
  File "/home/wzab/agwb/tests/test/../../src/addr_gen_wb.py", line 130, in <module>
    relax_ng = let.RelaxNG(relaxng_doc)
  File "src/lxml/relaxng.pxi", line 100, in lxml.etree.RelaxNG.__init__
lxml.etree.RelaxNGParseError: Element or text conflicts in interleave, line 16

Probably another approach is needed, where the "externals" will be marked with
another element name:
xblock instead of block
xsubblock instead of subblock
xsreg instead of sreg
xcreg instead of creg
xfield instead of field