Modified implementation so that it is compatible with VHDL < 2008
ghdl -a -g -C  --std=93c --ieee=standard hdl/wb_cdc.vhd
hdl/wb_cdc.vhd:143:28:error: conditional variable assignment not allowed before vhdl08
hdl/wb_cdc.vhd:150:42:error: conditional signal assignment not allowed in before vhdl08
hdl/wb_cdc.vhd:163:44:error: conditional signal assignment not allowed in before vhdl08
hdl/wb_cdc.vhd:170:42:error: conditional signal assignment not allowed in before vhdl08
hdl/wb_cdc.vhd:217:23:error: conditional variable assignment not allowed before vhdl08
hdl/wb_cdc.vhd:219:23:error: conditional variable assignment not allowed before vhdl08
hdl/wb_cdc.vhd:220:23:error: conditional variable assignment not allowed before vhdl08
ghdl:error: compilation error